---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# SurvivalFast

<!-- badges: start -->
<!-- badges: end -->

The goal of SurvivalFast is to ...

## Installation

You can install the development version of SurvivalFast from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("Lin-Wei-Han/survivalFast")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(SurvivalFast)
## basic example code
```

Remission times （in weeks） for two groups of leukemia patients:

```{r canser}
summary(canser)
```

For example（console的區域若太小，可能導致表格被截斷，而無法完整顯示）:

```{r}
survivalFast(canser$Week,            # 時間(必填)
             canser$Censord,         # 設限(必填)，需定義為：1 = event；0 = censor
             canser$Group,           # 分組(必填)，接受兩組以上
             y = 8,                  # 時間點，估計該時間點的統計量
             conf.level = 0.95,      # 信心水準，計算信賴區間。預設為0.95
             conf.type = "log",      # 計算信賴區間：plain(預設)；log。
             hazard.type = "Nelson", # 計算累積風險函數：likelihood(預設)；Nelson。
             plot = TRUE,            # 顯示圖表與否。預設為TRUE
             plot.conf = TRUE,       # 顯示信賴區間與否。預設為TRUE
             statistics = TRUE)      # 顯示統計量與否。預設為TRUE
```


